// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ricj_and_morti/features/characters/domain/entities/character.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterAdapter());
  }
}
